<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>TreeGrid.Demo</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TreeGrid.Wpf\TreeGrid.Wpf.csproj" />
    <ProjectReference Include="..\..\src\TreeGrid.Wpf.Export\TreeGrid.Wpf.Export.csproj" />
  </ItemGroup>

</Project>
